# -*- coding: utf-8 -*-
"""heart-disease-health-indicators-dataset-notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YL1p7dFyPlHl1TD-gdQsMjslbb6E4OvB

# Heart Disease Health Indicators Dataset Notebook

## Purpose
The purpose of this code notebook is to clean BRFSS data into a useable format for machine learning alogrithms.
The dataset originally has 330 features (columns), but based on heart disease research regarding factors influencing heart disease and other chronic health conditions, only select features are included in this analysis.

## Link to Dataset Output [Heart Disease Health Indicators Dataset](https://www.kaggle.com/alexteboul/heart-disease-health-indicators-dataset)
**253,680 survey responses from cleaned BRFSS 2015 - binary classification**

#### Important Risk Factors
Research in the field has identified the following as **important risk factors** for heart disease and other chronic illnesses like diabetes (not in strict order of importance):

*   blood pressure (high)
*   cholesterol (high)
*   smoking
*   diabetes
*   obesity
*   age
*   sex
*   race
*   diet
*   exercise
*   alcohol consumption
*   BMI
*   Household Income
*   Marital Status
*   Sleep
*   Time since last checkup
*   Education
*   Health care coverage
*   Mental Health

### Selected Subset of Features from BRFSS 2015
Given these risk factors, I tried to select features (columns/questions) in the BRFSS related to these risk factors. To help understand what the columns mean, I consult the BRFSS 2015 Codebook to see the questions and information about the questions. I try to match the variable names in the codebook to the variable names in the dataset I downloaded from Kaggle. I also reference some of the same features chosen for a research paper by Zidian Xie et al for *Building Risk Prediction Models for Type 2 Diabetes Using Machine Learning Techniques* using the 2014 BRFSS. Diabetes and Heart Disease outcomes are strongly correlated, with the primary cause of death for diabetics being heart disease complications. Given this information, it is a useful starting point.

**BRFSS 2015 Codebook:** https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf

**Relevant Research Paper using BRFSS for Diabetes ML:** https://www.cdc.gov/pcd/issues/2019/19_0109.htm


The **selected features** from the BRFSS 2015 dataset are:

**Response Variable / Dependent Variable:**
*   Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI) --> _MICHD


**Independent Variables:**

**High Blood Pressure**
*   Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional --> _RFHYPE5

**High Cholesterol**
*   Have you EVER been told by a doctor, nurse or other health professional that your blood cholesterol is high? --> TOLDHI2
*   Cholesterol check within past five years --> _CHOLCHK

**BMI**
*   Body Mass Index (BMI) --> _BMI5

**Smoking**
*   Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes] --> SMOKE100

**Other Chronic Health Conditions**
*   (Ever told) you had a stroke. --> CVDSTRK3
*   (Ever told) you have diabetes (If "Yes" and respondent is female, ask "Was this only when you were pregnant?". If Respondent says pre-diabetes or borderline diabetes, use response code 4.) --> DIABETE3

**Physical Activity**
*   Adults who reported doing physical activity or exercise during the past 30 days other than their regular job --> _TOTINDA

**Diet**
*   Consume Fruit 1 or more times per day --> _FRTLT1
*   Consume Vegetables 1 or more times per day --> _VEGLT1

**Alcohol Consumption**
*   Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) --> _RFDRHV5

**Health Care**
*   Do you have any kind of health care coverage, including health insurance, prepaid plans such as HMOs, or government plans such as Medicare, or Indian Health Service?  --> HLTHPLN1
*   Was there a time in the past 12 months when you needed to see a doctor but could not because of cost? --> MEDCOST

**Health General and Mental Health**
*   Would you say that in general your health is: --> GENHLTH
*   Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good? --> MENTHLTH
*   Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good? --> PHYSHLTH
*   Do you have serious difficulty walking or climbing stairs? --> DIFFWALK

**Demographics**
*   Indicate sex of respondent. --> SEX
*   Fourteen-level age category --> _AGEG5YR
*   What is the highest grade or year of school you completed? --> EDUCA
*   Is your annual household income from all sources: (If respondent refuses at any income level, code "Refused.") --> INCOME2

## 1. Get the data
"""
'''
# imports
import os
import pandas as pd
import random

random.seed(1)

# read in the dataset (select 2015)
year = "2015"
brfss_2015_dataset = pd.read_csv(f"2015.csv")

# How many rows and columns
brfss_2015_dataset.shape

# check that the data loaded in is in the correct format
pd.set_option("display.max_columns", 500)
brfss_2015_dataset.head()

"""**At this point we have 441,456 records and 330 columns. Each record contains an individual's BRFSS survey responses.**"""

# select specific columns
brfss_df_selected = brfss_2015_dataset[
    [
        "_MICHD",
        "_RFHYPE5",
        "TOLDHI2",
        "_CHOLCHK",
        "_BMI5",
        "SMOKE100",
        "CVDSTRK3",
        "DIABETE3",
        "_TOTINDA",
        "_FRTLT1",
        "_VEGLT1",
        "_RFDRHV5",
        "HLTHPLN1",
        "MEDCOST",
        "GENHLTH",
        "MENTHLTH",
        "PHYSHLTH",
        "DIFFWALK",
        "SEX",
        "_AGEG5YR",
        "EDUCA",
        "INCOME2",
    ]
]

brfss_df_selected.shape

brfss_df_selected.head()

"""## 2. Clean the data

### 2.1 Drop missing values
"""

# Drop Missing Values - knocks 100,000 rows out right away
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

"""### 2.2 Modify and clean the values to be more suitable to ML algorithms
In order to do this part, I referenced the codebook which says what each column/feature/question is: https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf
"""

# _MICHD
# Change 2 to 0 because this means did not have MI or CHD
brfss_df_selected["_MICHD"] = brfss_df_selected["_MICHD"].replace({2: 0})
brfss_df_selected._MICHD.unique()

# 1 _RFHYPE5
# Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
brfss_df_selected["_RFHYPE5"] = brfss_df_selected["_RFHYPE5"].replace({1: 0, 2: 1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE5 != 9]
brfss_df_selected._RFHYPE5.unique()

# 2 TOLDHI2
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected["TOLDHI2"] = brfss_df_selected["TOLDHI2"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI2 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI2 != 9]
brfss_df_selected.TOLDHI2.unique()

# 3 _CHOLCHK
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9
brfss_df_selected["_CHOLCHK"] = brfss_df_selected["_CHOLCHK"].replace({3: 0, 2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._CHOLCHK != 9]
brfss_df_selected._CHOLCHK.unique()

# 4 _BMI5 (no changes, just note that these are BMI * 100. So for example a BMI of 4018 is really 40.18)
brfss_df_selected["_BMI5"] = brfss_df_selected["_BMI5"].div(100).round(0)
brfss_df_selected._BMI5.unique()

# 5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected["SMOKE100"] = brfss_df_selected["SMOKE100"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

# 6 CVDSTRK3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected["CVDSTRK3"] = brfss_df_selected["CVDSTRK3"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

# 7 DIABETE3
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected["DIABETE3"] = brfss_df_selected["DIABETE3"].replace(
    {2: 0, 3: 0, 1: 2, 4: 1}
)
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE3 != 9]
brfss_df_selected.DIABETE3.unique()

# 8 _TOTINDA
# 1 for physical activity
# change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected["_TOTINDA"] = brfss_df_selected["_TOTINDA"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

# 9 _FRTLT1
# Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day
# remove all dont knows and missing 9
brfss_df_selected["_FRTLT1"] = brfss_df_selected["_FRTLT1"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1 != 9]
brfss_df_selected._FRTLT1.unique()

# 10 _VEGLT1
# Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day
# remove all dont knows and missing 9
brfss_df_selected["_VEGLT1"] = brfss_df_selected["_VEGLT1"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1 != 9]
brfss_df_selected._VEGLT1.unique()

# 11 _RFDRHV5
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# remove all dont knows and missing 9
brfss_df_selected["_RFDRHV5"] = brfss_df_selected["_RFDRHV5"].replace({1: 0, 2: 1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV5 != 9]
brfss_df_selected._RFDRHV5.unique()

# 12 HLTHPLN1
# 1 is yes, change 2 to 0 because it is No health care access
# remove 7 and 9 for don't know or refused
brfss_df_selected["HLTHPLN1"] = brfss_df_selected["HLTHPLN1"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.HLTHPLN1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.HLTHPLN1 != 9]
brfss_df_selected.HLTHPLN1.unique()

# 13 MEDCOST
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don/t know and 9 for refused
brfss_df_selected["MEDCOST"] = brfss_df_selected["MEDCOST"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST != 9]
brfss_df_selected.MEDCOST.unique()

# 14 GENHLTH
# This is an ordinal variable that I want to keep (1 is Excellent -> 5 is Poor)
# Remove 7 and 9 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

# 15 MENTHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected["MENTHLTH"] = brfss_df_selected["MENTHLTH"].replace({88: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

# 16 PHYSHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected["PHYSHLTH"] = brfss_df_selected["PHYSHLTH"].replace({88: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

# 17 DIFFWALK
# change 2 to 0 for no. 1 is already yes
# remove 7 and 9 for don't know not sure and refused
brfss_df_selected["DIFFWALK"] = brfss_df_selected["DIFFWALK"].replace({2: 0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

# 18 SEX
# in other words - is respondent male (somewhat arbitrarily chose this change because men are at higher risk for heart disease)
# change 2 to 0 (female as 0). Male is 1
brfss_df_selected["SEX"] = brfss_df_selected["SEX"].replace({2: 0})
brfss_df_selected.SEX.unique()

# 19 _AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

# 20 EDUCA
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove 9 for refused:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

# 21 INCOME2
# Variable is already ordinal with 1 being less than $10,000 all the way up to 8 being $75,000 or more
# Remove 77 and 99 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME2 != 99]
brfss_df_selected.INCOME2.unique()

# Check the shape of the dataset now: We have 253,680 cleaned rows and 22 columns (1 of which is our dependent variable)
brfss_df_selected.shape

# Let's see what the data looks like after Modifying Values
brfss_df_selected.head()

# Check Class Sizes of the heart disease column
brfss_df_selected.groupby(["_MICHD"]).size()

"""## 3. Make feature names more readable"""

# Rename the columns to make them more readable
brfss = brfss_df_selected.rename(
    columns={
        "_MICHD": "HeartDiseaseorAttack",
        "_RFHYPE5": "HighBP",
        "TOLDHI2": "HighChol",
        "_CHOLCHK": "CholCheck",
        "_BMI5": "BMI",
        "SMOKE100": "Smoker",
        "CVDSTRK3": "Stroke",
        "DIABETE3": "Diabetes",
        "_TOTINDA": "PhysActivity",
        "_FRTLT1": "Fruits",
        "_VEGLT1": "Veggies",
        "_RFDRHV5": "HvyAlcoholConsump",
        "HLTHPLN1": "AnyHealthcare",
        "MEDCOST": "NoDocbcCost",
        "GENHLTH": "GenHlth",
        "MENTHLTH": "MentHlth",
        "PHYSHLTH": "PhysHlth",
        "DIFFWALK": "DiffWalk",
        "SEX": "Sex",
        "_AGEG5YR": "Age",
        "EDUCA": "Education",
        "INCOME2": "Income",
    }
)

brfss.head()

brfss.shape

# Check how many respondents have had heart disease or a heart attack. Note the class imbalance!
brfss.groupby(["HeartDiseaseorAttack"]).size()

"""## 4. Save to csv
First save version where heart disease is the target variable and in the first column, then save one where diabetes is the target variable and in the first column.
"""

# ************************************************************************************************
brfss.to_csv("d2/x.csv", sep=",", index=False)
# ************************************************************************************************
y = brfss["HeartDiseaseorAttack"]
y.to_csv("d2/y.csv", sep=",", index=False)


'''

import pandas as pd
from sklearn.linear_model import LogisticRegression
from helpers import *
from implementations import *
from imblearn.over_sampling import SMOTE
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

y = np.genfromtxt("d2/y.csv", delimiter=",", skip_header=1)
x = np.genfromtxt("d2/x.csv", delimiter=",", skip_header=1)


ids = np.genfromtxt("test_ids.csv", delimiter=",")


def create_train_test_split(X, y, test_size=0.30, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state
    )
    return X_train, X_test, y_train, y_test


x_train, x_test, y_train, y_test = create_train_test_split(x, y)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(">>> After resample: \n --------------------------------------")
print(
    "ytrain -1: "
    + str(np.count_nonzero(y_train == 0))
    + "   |  ytrain 1: "
    + str(np.count_nonzero(y_train == 1))
    + "\n-------------------------------------"
)

over = SMOTE(sampling_strategy=0.15)
under = RandomUnderSampler(sampling_strategy=0.5)
steps = [("o", over), ("u", under)]
pipeline = Pipeline(steps=steps)
x_train, y_train = pipeline.fit_resample(x_train, y_train)

print(">>> After resample: \n --------------------------------------")
print(
    "ytrain -1: "
    + str(np.count_nonzero(y_train == 0))
    + "   |  ytrain 1: "
    + str(np.count_nonzero(y_train == 1))
    + "\n-------------------------------------"
)

gb_classifier = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_classifier.fit(x_train, y_train)
prediction = gb_classifier.predict(x_test)


precision = precision_score(y_test, prediction)
recall = recall_score(y_test, prediction)
f1score = f1_score(y_test, prediction)

print(f"Precision = {precision}")
print(f"Recall = {recall}")
print(f"F1 Score = {f1score}")
# Precision = 1.0
# Recall = 1.0
# F1 Score = 1.0
